// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalDriveApp.Data;

#nullable disable

namespace MinimalDriveApp.Migrations
{
    [DbContext(typeof(ArchiveStackDbContext))]
    partial class ArchiveStackDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("MinimalDriveApp.Models.KnownDrive", b =>
                {
                    b.Property<string>("SerialNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastBackedUp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("SerialNumber");

                    b.ToTable("KnownDrives");
                });
#pragma warning restore 612, 618
        }
    }
}
